workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:
      - name: Build debug apk
        script: ./gradlew assembleDebug
      - name: Make executable
        script: chmod -x gradlew
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - garglakshay56@gmail.com
